# Generated by Django 5.1.2 on 2024-11-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='is_cover',
            field=models.BooleanField(),
        ),
    ]
