# Generated by Django 5.1.2 on 2024-11-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_primarygroup_secondarygroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='PrimaryGroup',
        ),
        migrations.DeleteModel(
            name='SecondaryGroup',
        ),
    ]
