# Generated by Django 5.1.2 on 2024-11-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0012_saleinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinfo',
            name='secondary_group',
        ),
        migrations.RemoveField(
            model_name='saleinfo',
            name='primary_group',
        ),
        migrations.RemoveField(
            model_name='saleinfo',
            name='product',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='SaleInfo',
        ),
    ]
