# Generated by Django 5.1.2 on 2024-11-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0014_group_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('primary_attr', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pri_attr', to='ecommerceapp.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.product')),
                ('secondary_attr', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sec_attr', to='ecommerceapp.attribute')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
