# Generated by Django 5.1.2 on 2024-11-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0015_saleinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('province_city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('ward_commune', models.CharField(max_length=100)),
                ('address_details', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('is_default', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('home', 'Home'), ('office', 'Office')], default='home', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
