# Generated by Django 5.1.2 on 2024-12-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0016_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(blank=True, default=None, related_name='user', to='ecommerceapp.address'),
        ),
    ]
