# Generated by Django 5.1.2 on 2024-12-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0026_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, default=None, max_length=255)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('image', models.CharField(blank=True, default=None, max_length=255)),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerceapp.order')),
                ('sale_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.saleinfo')),
            ],
        ),
    ]
