# Generated by Django 5.1.2 on 2024-12-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0028_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='addresses',
        ),
    ]
