# Generated by Django 5.1.2 on 2024-12-02 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0029_remove_shop_address_remove_user_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='shop',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.shop', unique=True),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
