# Generated by Django 5.1.2 on 2024-12-02 15:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0032_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
