# Generated by Django 5.1.2 on 2024-12-10 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0035_alter_product_brand_alter_product_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinfo',
            name='primary_attr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pri_attr', to='ecommerceapp.attribute'),
        ),
        migrations.AlterField(
            model_name='saleinfo',
            name='secondary_attr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sec_attr', to='ecommerceapp.attribute'),
        ),
    ]
