# Generated by Django 5.1.2 on 2025-01-25 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0038_alter_provincecity_name_childcatelv1_childcatelv2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='shop',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.shop'),
        ),
    ]
