# Generated by Django 5.1.2 on 2025-01-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0039_alter_address_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
