# Generated by Django 5.1.2 on 2025-01-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0041_product_childcatelv1_product_childcatelv2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcatelv1',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='childcatelv2',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
