# Generated by Django 5.1.2 on 2025-01-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0042_alter_childcatelv1_name_alter_childcatelv2_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerceapp.category')),
                ('childCateLv1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerceapp.childcatelv1')),
                ('childCateLv2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerceapp.childcatelv2')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
