# Generated by Django 5.1.2 on 2025-01-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0043_labeldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLabelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=255)),
                ('labelDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.labeldetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='labelDetails',
            field=models.ManyToManyField(through='ecommerceapp.ProductLabelDetails', to='ecommerceapp.labeldetails'),
        ),
    ]
