# Generated by Django 5.1.2 on 2025-01-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0044_productlabeldetails_product_labeldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='group',
        ),
        migrations.RemoveField(
            model_name='saleinfo',
            name='primary_attr',
        ),
        migrations.RemoveField(
            model_name='saleinfo',
            name='secondary_attr',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
