# Generated by Django 5.1.2 on 2025-01-29 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0045_remove_attribute_group_remove_saleinfo_primary_attr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='saleinfo',
            name='nd_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nd_attribute', to='ecommerceapp.groupattribute'),
        ),
        migrations.AddField(
            model_name='saleinfo',
            name='st_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='st_attribute', to='ecommerceapp.groupattribute'),
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('is_main', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='groupattribute',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.productgroup'),
        ),
    ]
