# Generated by Django 5.1.2 on 2025-01-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0046_groupattribute_saleinfo_nd_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemSalesInfo',
            field=models.ManyToManyField(through='ecommerceapp.OrderItem', to='ecommerceapp.saleinfo'),
        ),
    ]
