# Generated by Django 5.1.2 on 2025-01-31 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0047_order_itemsalesinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcatelv1',
            name='superCate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childcatelv1', to='ecommerceapp.category'),
        ),
        migrations.AlterField(
            model_name='childcatelv2',
            name='superCate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childcatelv2', to='ecommerceapp.childcatelv1'),
        ),
    ]
