# Generated by Django 5.1.2 on 2025-02-02 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0049_alter_district_locatedin_alter_wardcommune_locatedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerceapp.role'),
        ),
    ]
