# Generated by Django 5.1.2 on 2025-02-02 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0050_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChildCateLv1',
            new_name='ChildCate',
        ),
        migrations.RemoveField(
            model_name='labeldetails',
            name='childCateLv2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='childCateLv2',
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChildCateLv2',
        ),
    ]
