# Generated by Django 5.1.2 on 2025-02-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0051_rename_childcatelv1_childcate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='childCateLv1',
            new_name='childCate',
        ),
        migrations.AlterField(
            model_name='childcate',
            name='superCate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childcate', to='ecommerceapp.category'),
        ),
    ]
