# Generated by Django 5.1.2 on 2025-02-04 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0052_rename_childcatelv1_product_childcate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_images', to='ecommerceapp.review'),
        ),
    ]
