# Generated by Django 5.1.2 on 2025-02-04 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0053_alter_reviewimage_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='shop',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_address', to='ecommerceapp.shop'),
        ),
    ]
