# Generated by Django 5.1.2 on 2025-02-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0055_alter_shop_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeldetails',
            old_name='childCateLv1',
            new_name='childCate',
        ),
    ]
