# Generated by Django 5.1.2 on 2025-02-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0056_rename_childcatelv1_labeldetails_childcate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeldetails',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cate_lb_details', to='ecommerceapp.category'),
        ),
        migrations.AlterField(
            model_name='labeldetails',
            name='childCate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childcate_lb_details', to='ecommerceapp.childcate'),
        ),
    ]
