# Generated by Django 5.1.2 on 2025-02-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0057_alter_labeldetails_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcate',
            name='superCate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='ecommerceapp.category'),
        ),
    ]
