# Generated by Django 5.1.2 on 2025-02-04 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0059_alter_groupattribute_product_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sales_info', to='ecommerceapp.product'),
        ),
    ]
