# Generated by Django 5.1.2 on 2025-02-05 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0060_alter_saleinfo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlabeldetails',
            name='labelDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_value', to='ecommerceapp.labeldetails'),
        ),
        migrations.AlterField(
            model_name='productlabeldetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='ecommerceapp.product'),
        ),
    ]
